config/routes.rb
Rails.application.routes.draw do

  resources :event_bookings
  devise_for :users, controllers: {registrations: 'registrations'}

  scope "/admin" do 
    resources :users
  end

  resources :venues

  resources :venue_bookings

  get 'events/my_events'
  resources :events do 
    resources :event_bookings
  end
  resources :categories

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/event_booking.rb
class EventBooking < ActiveRecord::Base
	belongs_to :event
	belongs_to :user
	before_create :calculate_price
	after_create :minus_tickets_left

	validate :check_ticket_availability

	private

	def calculate_price
		self.total_price = self.event.entry_fee * self.tickets
	end

	def minus_tickets_left
		event = self.event
		tickets = event.tickets_left - self.tickets
		event.update_attributes(tickets_left: tickets)
		
	end

	def check_ticket_availability
		if self.event.tickets_left <= 0
			errors.add(:event, "Tickets are sold out!")
		elsif self.event.tickets_left < self.tickets
			errors.add(:event, "Only few tickets left. Choose a lesser number of tickets.")
		end
	end

end

app/controllers/event_bookings_controller.rb
class EventBookingsController < ApplicationController
  before_action :set_event_booking, only: [:show, :edit, :update, :destroy]

  # GET /event_bookings
  # GET /event_bookings.json
  def index
    @event_bookings = EventBooking.all
  end

  # GET /event_bookings/1
  # GET /event_bookings/1.json
  def show
  end

  # GET /event_bookings/new
  def new
    @event_booking = EventBooking.new

  end

  # GET /event_bookings/1/edit
  def edit
  end

  # POST /event_bookings
  # POST /event_bookings.json
  def create
    @event_booking = EventBooking.new(event_booking_params)
    @event_booking.user_id = current_user.id
    @event_booking.event_id = params[:event_id]
    respond_to do |format|
      if @event_booking.save
        format.html { redirect_to event_path(@event_booking.event_id, booking_id: @event_booking.id), notice: 'Event booking was successfully created.' }
        format.json { render :show, status: :created, location: @event_booking }
      else
        format.html { render :new }
        format.json { render json: @event_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_bookings/1
  # PATCH/PUT /event_bookings/1.json
  def update
    respond_to do |format|
      if @event_booking.update(event_booking_params)
        format.html { redirect_to @event_booking, notice: 'Event booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_booking }
      else
        format.html { render :edit }
        format.json { render json: @event_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_bookings/1
  # DELETE /event_bookings/1.json
  def destroy
    @event_booking.destroy
    respond_to do |format|
      format.html { redirect_to event_bookings_url, notice: 'Event booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_booking
      @event_booking = EventBooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_booking_params
      params.require(:event_booking).permit(:event_id, :user_id, :tickets, :total_price)
    end
end

app/helpers/event_bookings_helper.rb
module EventBookingsHelper
end

app/views/event_bookings/_form.html.erb
<%= form_for(@event_booking) do |f| %>
  <% if @event_booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_booking.errors.count, "error") %> prohibited this event_booking from being saved:</h2>

      <ul>
      <% @event_booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_bookings/edit.html.erb
<h1>Editing Event Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_booking %> |
<%= link_to 'Back', event_bookings_path %>

app/views/event_bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Event Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_bookings.each do |event_booking| %>
      <tr>
        <td><%= event_booking.event_id %></td>
        <td><%= event_booking.user_id %></td>
        <td><%= link_to 'Show', event_booking %></td>
        <td><%= link_to 'Edit', edit_event_booking_path(event_booking) %></td>
        <td><%= link_to 'Destroy', event_booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event booking', new_event_booking_path %>

app/views/event_bookings/new.html.erb
<h1>New Event Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', event_bookings_path %>

app/views/event_bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @event_booking.event_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @event_booking.user_id %>
</p>

<%= link_to 'Edit', edit_event_booking_path(@event_booking) %> |
<%= link_to 'Back', event_bookings_path %>