config/routes.rb
Rails.application.routes.draw do

  resources :event_bookings
  devise_for :users, controllers: {registrations: 'registrations'}

  scope "/admin" do 
    resources :users
  end

  resources :venues

  resources :venue_bookings

  get 'events/my_events'
  resources :events do 
    resources :event_bookings
  end
  resources :categories

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/event.rb
class Event < ActiveRecord::Base

	mount_uploader :avatar, AvatarUploader

	has_many :venue_bookings
	has_many :event_bookings
	has_many :event_categories
	has_many :categories, through: :event_categories


	belongs_to :city
	belongs_to :venue
	belongs_to :locality
	belongs_to :user

	validate :slot_open?, on: :create
	validate :check_date, on: :create

	#validates_presence_of :name

	def self.search(search)
		where("name LIKE ?", "%#{search}%")
		#where("description LIKE ?", "%#{search}%")
	end

	private 

	def slot_open?
		bookings = self.venue.venue_bookings
		bookings.each do |booking|
			if self.start_datetime.between?(booking.start_datetime, booking.end_datetime) || self.end_datetime.between?(booking.start_datetime, booking.end_datetime)
				errors.add( :venue ," is already booked for that time slot!")
			end
		end
	end

	def check_date
		if self.start_datetime >= self.end_datetime
			errors.add(:start_datetime," is invalid!")	
		end
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]
	load_and_authorize_resource

	def index
		@events = Event.all
		@categories = Category.all
		if params[:search]
			@events = Event.search(params[:search])
		else
			@events = Event.all 
		end
	end

	def new
		@event = Event.new
		
	end

	def create
		@event = Event.new(event_params)
		@event.locality_id = @event.venue.locality_id
		@event.user_id = current_user.id

		if @event.save
			@venue_booking = VenueBooking.create(start_datetime: @event.start_datetime, end_datetime: @event.end_datetime, venue_id: @event.venue_id, event_id: @event.id)
			redirect_to events_path, notice: "Successfully added!"
		else
			render action: "new"
		end
	end

	def show
		@event = Event.find(params[:id])
		@event_booking = EventBooking.new
		@event_bookings = @event.event_bookings

		if params[:booking_id]
			@booking_confirmed = EventBooking.find(params[:booking_id])
		end
	end

	def edit
		@event = Event.find(params[:id])
	end
	
	def update
		@event = Event.find(params[:id])
		if @event.update_attributes(event_params)
			redirect_to events_path,notice: "Updated successfully!"
		else
			render action: "edit"
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path, notice: "Deleted successfully!" 
	end

	def my_events
		@events = current_user.events
		@categories = Category.all
	end

	private

	def event_params
		params[:event].permit(:name, :description, :venue_id, :city_id, :start_datetime, :end_datetime, :entry_fee, :status, :locality_id, :tickets_left, :avatar, category_ids: [])
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: {class: "form-horizontal"} do |f| %>
	<% if @event.errors.any? %>
		<div class="alert alert-danger">
			<h3>These errors prohibited the form from being created:</h3>
			<ul>
				<% @event.errors.full_messages.each do |msg| %>
				<li><%= msg%></li>
				<% end %>
			</ul>			
		</div>	
	<% end %>
	

	<div class="form-group">
			<%= f.label :name %>
	<%= f.text_field :name, class: "form-control" %>		
	</div>

	
	<div class="form-group">
			<%= f.label :avatar %>
	<%= f.file_field :avatar, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :description %>
	<%= f.text_area :description, class: "form-control" %> 		
	</div>


	<div class="form-group" >
		<%= f.label :venue_id %>
	<%= f.collection_select :venue_id, Venue.all, :id, :name, prompt: "Select venue" ,class: "form-control" %>		
	</div>

	<div class="form-group">
		<%= f.label "Starting at" %>
	<%= f.text_field :start_datetime, id: "startDatetime",class: "form-control" %> 
	</div>

	<div class="form-group">
		<%= f.label "Ending at" %>
	<%= f.text_field :end_datetime, id: "endDatetime",class: "form-control" %> 
	</div>
	

	<div class="form-group">
		<%= f.label :entry_fee %>
	<%= f.number_field :entry_fee,class: "form-control" %> 
	</div>

	<div class="form-group">
		<%= f.label :status %>
	<%= f.select :status, ["New", "On-going", "Over"],class: "form-control" %> 	
	</div>
	

	<div class="form-group">
		<%= f.collection_check_boxes :category_ids, Category.all, :id, :name,class: "form-control" %> 
	</div>
	
	
	<div class="form-group">
		<%= f.label "Tickets" %>
	<%= f.select :tickets_left, value: [250,500,750,1000],class: "form-control" %>
	</div>

	<%= f.submit "Submit", class: "btn btn-success"%>
</div>
<% end %>

app/views/events/_tab.html.erb
<ul class="nav nav-tabs" >

  <% if current_page? "/events"%>
  <li role="presentation" class="active"> 
	<% else %>
  <li role="presentation" >
  <%end%>
    <a href="/events">Home</a>
  </li>


	<% if can? :my_events, Event.new %>
	   <% if current_page? "/events/my_events"%>
      <li role="presentation" class="active"> 
      <% else %>
      <li role="presentation" >
      <%end%>
        <a href="/events/my_events">My Events</a>
      </li>
	<%end%>

  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Categories <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <% @categories.each do |category| %>
      	<li><%= link_to category.name.capitalize, category_path(category) %></li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/events/edit.html.erb
<div class="container">

	<div class="page-header">
		<h3>Edit Event - <%= @event.name %></h3>
	</div>
	
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
	

</div>

app/views/events/index.html.erb
	
<div class="jumbotron jumbotron-events" >
  <div class="container" >
    <div style="margin-top: 100px">
	<div class="page-header text-center">
		<p>
			<% if params[:search] == nil %>
				<h3>All Events</h3>
			<% else %>
				<h3>Events with "<%= params[:search] %>" : </h3>
			<% end %>
		</p>
	</div>
	<div class="text-center">
		<h4><% if can? :my_events, Event.new %>
			Goto <%= link_to "My Events", events_my_events_path %>  
			<%end%>
			<% if can? :create, Event.new %>
				or <%= link_to "Create Event", new_event_path, class: "btn btn-info" %>
			<% end %>
		</h4>

		<%= form_tag(events_path, method: "get", class: "form-inline") do %>
			<%= text_field_tag :search, params[:search], prompt: "Enter a keyword...", class: "form-control" %>
			<%= submit_tag "Search",class: "btn btn-default" %>
		<% end %>
	</div>

  </div>
  </div>
</div>

<div class="container">

<%= render 'tab' %>



<div class="row">
	<% @events.each do |event|%>
	<div class="col-12 col-sm-6 col-md-4 col-lg-3">
		<div class="card">
		  <%= link_to image_tag(event.avatar.url, height: "150px", width: "100%"), event_path(event) %>
		  <div class="card-padding">

        <!-- Event Header -->
		  	<div class="row">
		  		<h4 class="text-center"><%= link_to "#{event.name}", event_path(event) %></h4>
		  	</div>
	      
        <!-- Event Control Panel -->
        <div class="row">
        	<div class="col-md-8"> 
        		<p class="text-left"><%= event.categories.pluck(:name).map { |e| e.capitalize }.join(', ') %></p>
        	</div>
        	<div class="col-md-4">
        		<p class="text-center">
        			<%= link_to event_path(event) do%>
    						<span class="glyphicon glyphicon-eye-open"></span>
    					<%end%>
    					<% if can? :update, event %>
    						<%= link_to edit_event_path(event) do %>
    							<span class="glyphicon glyphicon-pencil"></span>
    						<%end%>
    						<%= link_to event_path(event), method: :delete, data: {confirm: "Are you sure?"} do %>
    							<span class="glyphicon glyphicon-trash"></span>
    						<%end%>	
    					<% end %>
        		</p>
        	</div>
        </div>
        
        <!-- Event Date & Buy -->
        <div class="row">
        	<div class="col-sm-6 col-md-6 ">
        		<p class="text-center well well-sm"> <small><%= event.end_datetime.strftime("%d %b %Y") %></small></p>
        	</div>
        	<div class="col-sm-6 col-md-6" style="margin-top:2px">
        		<p class="text-center"><a href="/events/<%= "#{event.id}" %>" class="btn btn-danger" role="button" style="border: none; color: white;">Buy Tickets</a></p>
        	</div>
        </div>

		  </div>
		</div>
	</div>
	<%end%>
</div>
</div>

app/views/events/my_events.html.erb
	
<div class="jumbotron jumbotron-events" >
  <div class="container">
    <div style="margin-top: 100px">
	<div class="page-header text-center">
		<p>
			<% if params[:search] == nil %>
				<h3>My Events</h3>
			<% else %>
				<h3>Events with "<%= params[:search] %>" : </h3>
			<% end %>
		</p>
	</div>
	<div class="text-center">
		<h4><% if can? :my_events, Event.new %>
			Goto <%= link_to "My Events", events_my_events_path %> 
			<%end%>
			<% if can? :create, Event.new %>
				or <%= link_to "Create Event", new_event_path, class: "btn btn-info" %>
			<% end %>
		</h4>

		<%= form_tag(events_path, method: "get", class: "form-inline") do %>
			<%= text_field_tag :search, params[:search], prompt: "Enter a keyword...", class: "form-control" %>
			<%= submit_tag "Search",class: "btn btn-default" %>
		<% end %>
	</div>
	</div>
  </div>
</div>

<div class="container">
	
<%= render 'tab' %>


<div class="row">
	<% @events.each do |event|%>
	<div class="col-sm-6 col-md-3">
		<div class="card">
		  <%= link_to image_tag(event.avatar.url, height: "150px", width: "100%"), event_path(event) %>
		  <div class="card-padding">
		  	<div class="row">
		  		<h4 style="margin-left:8px;"><%= link_to "#{event.name}", event_path(event) %></h4>
		  	</div>
	        
	        <div class="row">
	        	<div class="col-md-8">
	        		<p class="text-left"><%= event.categories.pluck(:name).map { |e| e.capitalize }.join(', ') %></p>
	        	</div>
	        	<div class="col-md-4">
	        		<p class="text-center">
	        			<%= link_to event_path(event) do%>
							<span class="glyphicon glyphicon-eye-open"></span>
						<%end%>
						<% if can? :update, event %>
							<%= link_to edit_event_path(event) do %>
								<span class="glyphicon glyphicon-pencil"></span>
							<%end%>
							<%= link_to event_path(event), method: :delete, data: {confirm: "Are you sure?"} do %>
								<span class="glyphicon glyphicon-trash"></span>
							<%end%>	
						<% end %>
	        		</p>
	        	</div>
	        </div>

	        <div class="row">
	        	<div class="col-md-6 ">
	        		<p class="text-center well well-sm"> <small><%= event.end_datetime.strftime("%d %b %Y") %></small></p>
	        	</div>
	        	<div class="col-md-6" style="margin-top:2px">
	        		<p ><a href="/events/<%= "#{event.id}" %>" class="btn btn-danger" role="button" style="border: none; color: white;">Buy Tickets</a></p>
	        	</div>
	        </div>
		  </div>
		</div>
	</div>
	<%end%>
</div>

</div>

app/views/events/new.html.erb
<div class="container">

	<div class="page-header">
		<h3>Create Event</h3>
	</div>
	
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
	

</div>

app/views/events/show.html.erb
<div class="container">
	

	<div class="page-header">
		<ol class="breadcrumb">
			<li><%= link_to "Events", events_path %></li>
			<li class="active"><%= link_to @event.name, event_path(@event) %></li>
		</ol>
		<h2><%= @event.name %><sup> <small> <em> <%= @event.status %></em></small></sup></h2>
	</div>

	<div class="row">
		<div class="col-md-7" >
			<!-- carousel starts here -->
			<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="width:600px">
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
			  </ol>

			  <!-- Wrapper for slides -->
			  <div class="carousel-inner" role="listbox">
			    <div class="item active">
			      <%= image_tag(@event.avatar.url) if @event.avatar %>
			      <div class="carousel-caption">
			       Image 1
			      </div>
			    </div>
			    <div class="item">
			      <%= image_tag(@event.avatar.url, height: "400px") if @event.avatar %>
			      <div class="carousel-caption">
			        Image 2
			      </div>
			    </div>
				<div class="item">
			      <%= image_tag(@event.avatar.url, height: "400px") if @event.avatar %>
			      <div class="carousel-caption">
			        Image 2
			      </div>
			    </div>  
			  </div>

			  <!-- Controls -->
			  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
			    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
			    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
			<!-- carousel ends here -->		
		</div> 

		<div class="col-md-5">
			<% if params[:booking_id] %>
			<div class="alert alert-success text-center">
				<h3>Booked successfully! <br> Total Price : <b>Rs. <%= @booking_confirmed.total_price %></b></h3> <br>
			</div>
			<%end %>

			<b><%= @event.description %> </b><br/>
			<b>Venue : </b> <%= link_to "#{@event.venue.name}", venue_path(@event.venue) %> <br>
			<b>Starting from :</b> <%= @event.start_datetime.strftime("%d %B %Y - %I:%M %P ") %> <br/>
			<b>Ending at :</b> <%= @event.end_datetime.strftime("%d %B %Y - %I:%M %P ") %>

			<div >
			<% if can? :create, @event_booking %>
			<div class="well" style="width:50%">
				
				<h3 style="margin-top:5px">Buy Tickets</h3>
				<b>Entry fee :</b> Rs.<%= @event.entry_fee %> <br/>
				<%= form_for([@event,@event_booking]) do |f|  %>
					
					<% @event_booking.tickets = 0 %>
					<%= f.label "Choose no of tickets" %>
					<%= f.select :tickets, [1,2,3,4,5,6,7,8,9,10] %> 
				
					<% @event_booking.total_price = @event.entry_fee * @event_booking.tickets %>
				 
					<%= f.submit "Book" , class: "btn btn-danger"%> <br>
					
				<% end %>	
			</div>
			<% end %>

			<div>
				
				<h3>
					Tickets Left:
					<span class="alert alert-info"><%= @event.tickets_left %></span>	
				</h3>
			</div>
		</div>
		</div>

		
	</div>
	
	<div class="row">
		<div class="col-md-8">
			<% if can? :update, @event.event_bookings.first %>
			<h3>Bookings</h3>

			<table class="table table-bordered">
				<thead>
					<tr>
						<th>#</th>
						<th>User</th>
						<th>Email</th>
						<th>Tickets Booked</th>
						<th>Price</th>
					</tr>
				</thead>
				<tbody>
					<% 	i = 1
						sum = 0
						tickets = 0 %>
					<% @event_bookings.each do |booking| %>
					<tr>
						<td><%= i %></td>
						<td><%= booking.user.username %></td>
						<td><%= booking.user.email %></td>
						<td><%= booking.tickets %></td>
						<td>Rs. <%= booking.total_price %></td>
						<% 	i += 1
							sum += booking.total_price 
							tickets += booking.tickets %>
					</tr>
					<%end %>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>Total Tickets : <b><%= tickets %></b></td>
						<td><b>Rs. <%= sum %></b></td>
					</tr>
				</tbody>
			</table>
			<% end %>
					
		</div>
	</div>
	
</div>