config/routes.rb
Rails.application.routes.draw do

  resources :event_bookings
  devise_for :users, controllers: {registrations: 'registrations'}

  scope "/admin" do 
    resources :users
  end

  resources :venues

  resources :venue_bookings

  get 'events/my_events'
  resources :events do 
    resources :event_bookings
  end
  resources :categories

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/venue.rb
class Venue < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader

	has_many :venue_bookings
	has_many :events
	
	belongs_to :locality
	belongs_to :user
	belongs_to :city

	def self.search(search)
		where("name LIKE ?", "%#{search}%")
		#where("description LIKE ?", "%#{search}%")
	end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	load_and_authorize_resource
	
	def index
		@venues = Venue.all 
		@categories = Category.all
		if params[:search]
			@venues = Venue.search(params[:search])
		else
			@venues = Venue.all 
		end
	end

	def new
		@venue = Venue.new
	end

	def create
		@venue = Venue.new(venue_params)
		@venue.user_id = current_user.id
		if @venue.save
			redirect_to venues_path, notice: "Successfully added venue!"
		else
			render action: "new"
		end
	end

	def show
		@venue = Venue.find(params[:id])
		@venue_booking = VenueBooking.new
	end

	def edit
		@venue = Venue.find(params[:id])
	end

	def update
		@venue = Venue.find(params[:id])
		if @venue.update_attributes(venue_params)
			redirect_to venues_path, notice: "Updated Successfully!"
		else
			render action: "edit"
		end
	end

	def destroy
		@venue = Venue.find(params[:id])
		@venue.destroy
		redirect_to venues_path, notice: "Deleted successfully!" 
	end

	private

	def venue_params
		params[:venue].permit(:name, :locality_id, :address, :user_id, :seats, :avatar)
	end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_js.html.erb
<% if !@venue.new_record? %>
	
	<script>
		$(document).ready(function() {
			$('#calendar').fullCalendar({
				defaultDate: '<%= Date.today.strftime("%Y-%m-%d") %>',
				eventLimit: true, // allow "more" link when too many events
				events: [
					<% @venue.venue_bookings.each do |booking| %>
					{
						<% if !booking.event.nil? %>
							title: "<%= booking.event.name.capitalize %>",
						<% else %>
							title: "*Booked by VenueOwner*",
						<%end%>
						
						start: "<%= booking.start_datetime.strftime("%Y-%m-%d") %>",
						end: "<%= booking.end_datetime.strftime("%Y-%m-%d") %>"
					},
					<% end %>
				]
			});
		});
	</script>

<%end%>

app/views/venues/_tab.html.erb
<ul class="nav nav-tabs" >
	<li role="presentation" class="active"> <a href="/events">Home</a></li>
	
	<% if can? :my_events, Event.new %>
		<li role="presentation"> <a href="/events/my_events">My Events</a></li>
	<%end%>

  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Categories <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <% @categories.each do |category| %>
      	<li><%= link_to category.name.capitalize, category_path(category) %></li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/venues/edit.html.erb
<div class="container">
<div class="page-header">
	<h3>Edit Venue - <%= @venue.name %></h3>	
</div>


<div class="col-md-4">
<%= form_for @venue, html: {class: "form-horizontal"} do |f| %>

	<% if @venue.errors.any? %>
		<div class="alert alert-danger">
			<h3>These errors prohibited the form from being created:</h3>
			<ul>
				<% @venue.errors.full_messages.each do |msg| %>
				<li><%= msg%></li>
				<% end %>
			</ul>			
		</div>	
	<% end %>
	
	<div class="form-group">
		<%= f.label :name %>
	<%= f.text_field :name,class: "form-control" %>
	</div>
	
	<div class="form-group">
	<%= f.label :avatar %> 
	<%= f.file_field :avatar,class: "form-control" %>
	</div>

	<div class="form-group">
	<%= f.label :address %>
	<%= f.text_area :address,class: "form-control" %> 
	</div>	

	<div class="form-group">
	<%= f.label :locality_id %>
	<%= f.collection_select :locality_id, Locality.all, :id, :name, prompt: "Select your locality" %>
	</div>

	<div class="form-group">
	<%= f.label "Seats(if any)" %>
	<%= f.number_field :seats,class: "form-control" %> 
	</div>

	<%= f.submit "Update Venue", class: "btn btn-success" %>

<% end %>
</div>
</div>

app/views/venues/index.html.erb
	
<div class="jumbotron jumbotron-venues"  >
  <div class="container">
    <div style="margin-top: 100px">
	<div class="page-header text-center">
		<p>
			<% if params[:search] == nil %>
				<h3>All Venues</h3>
			<% else %>
				<h3>Venues with "<%= params[:search] %>" : </h3>
			<% end %>
		</p>
	</div>
	<div class="text-center">
		<h4><% if can? :my_events, Event.new %>
			Goto <%= link_to "My Events", events_my_events_path %> 
			<%end%>
			<% if can? :create, Venue.new %>
				Or,
				<%= link_to "Add a venue", new_venue_path, class: "btn btn-info" %> 
			<% end %>
		</h4>

		<%= form_tag(venues_path, method: "get", class: "form-inline") do %>
			<%= text_field_tag :search, params[:search], prompt: "Enter a keyword...", class: "form-control" %>
			<%= submit_tag "Search",class: "btn btn-default" %>
		<% end %>
	</div>
	</div>
  </div>
</div>




<div class="container">
	
	<%= render 'tab' %>

<div class="row">
	<% @venues.each do |venue|%>
	<div class="col-12 col-sm-6 col-md-4 col-lg-3">
		<div class="card">
		  <%= link_to image_tag(venue.avatar.url , height: "150px", width: "100%"), venue_path(venue) %>
		  <div class="card-padding">
		  	<div class="row">
		  		<h4 class="text-center"><%= link_to "#{venue.name}", venue_path(venue) %></h4>
		  	</div>
	        
        <div class="row">
        	<div class="col-md-8">
        		<p class="text-center"><%= venue.locality.city.name %></p>
        	</div>
        	<div class="col-md-4">
        		<p class="text-center">
        			<%= link_to venue_path(venue) do%>
						<span class="glyphicon glyphicon-eye-open"></span>
					<%end%>
					<% if can? :update, venue %>
						<%= link_to edit_venue_path(venue) do %>
							<span class="glyphicon glyphicon-pencil"></span>
						<%end%>
						<%= link_to venue_path(venue), method: :delete, data: {confirm: "Are you sure?"} do %>
							<span class="glyphicon glyphicon-trash"></span>
						<%end%>	
					<% end %>
        		</p>
        	</div>
        </div>

        <div class="row">
        	<div class="col-sm-6 col-md-6 ">
        		<p class="text-center well well-sm"> <small><%= venue.seats %> seats</small></p>
        	</div>
        	<div class="col-sm-6 col-md-6" style="margin-top:2px">
        		<p class="text-center"><a href="/venues/<%= "#{venue.id}" %>" class="btn btn-danger" role="button" style="border: none; color: white;">Book Venue</a></p>
        	</div>
        </div>
		  </div>
		</div>
	</div>
	<%end%>
</div>
</div>

app/views/venues/new.html.erb
<div class="container">
<div class="page-header">
	<h3>Add a new Venue</h3>	
</div>


<div class="col-md-4">
<%= form_for @venue, html: {class: "form-horizontal"} do |f| %>

	<% if @venue.errors.any? %>
		<div class="alert alert-danger">
			<h3>These errors prohibited the form from being created:</h3>
			<ul>
				<% @venue.errors.full_messages.each do |msg| %>
				<li><%= msg%></li>
				<% end %>
			</ul>			
		</div>	
	<% end %>
	
	<div class="form-group">
		<%= f.label :name %>
	<%= f.text_field :name,class: "form-control" %>
	</div>
	
	<div class="form-group">
	<%= f.label :avatar %> 
	<%= f.file_field :avatar,class: "form-control" %>
	</div>

	<div class="form-group">
	<%= f.label :address %>
	<%= f.text_area :address,class: "form-control" %> 
	</div>	

	<div class="form-group">
	<%= f.label :locality_id %>
	<%= f.collection_select :locality_id, Locality.all, :id, :name, prompt: "Select your locality" %>
	</div>

	<div class="form-group">
	<%= f.label "Seats(if any)" %>
	<%= f.number_field :seats,class: "form-control" %> 
	</div>

	<%= f.submit "Add Venue", class: "btn btn-success" %>

<% end %>
</div>
</div>

app/views/venues/show.html.erb
<%= render 'js' %>


<div class="container">
	
	<div class="page-header">
		<ol class="breadcrumb">
			<li><%= link_to "Venues", venues_path %></li>
			<li class="active"><%= link_to @venue.name, venue_path(@venue) %></li>
		</ol>
		<h3><%= @venue.name %></h3>
	</div>

	<div class="row">
		<div class="col-md-6">
			
			<%= image_tag(@venue.avatar.url, display: "block", width: "100%", margin: "auto" ) if @venue.avatar.url %>
			<div class="row" style="margin-top:20px">
				<div class="col-md-6" >
					<p> <b>Owned by : </b><%= @venue.user.username %></p>
					<p><b>Address : </b><%= @venue.address %></p>
				</div>
				<div class="col-md-5 well">
					<h4>Seat Capacity : <b><%= @venue.seats %></b></h4>
				</div>
			</div>
			
		</div>

		<div class="col-md-6">
				<div id="calendar"></div>	
		</div>
	</div>


	<div class="row">
		
		<div class="col-md-7">
			<div class="page-header">
					<h3>Bookings</h3>
			</div>
			<table class="table table-bordered", >
				<tr>
					<th>#</th>
					<th>Event</th>
					<th>Starts on</th>
					<th>Ends at</th>
				</tr>
				<% @venue.venue_bookings.each_with_index do |booking, i| %>
				<tr>
					<td>
						<%= i +=1 %>		
					</td>
					<td>
						<% if !booking.event.nil? %>
							<%= booking.event.name.capitalize %>
						<% else %>
							<p>*Booked by VenueOwner*</p>
						<%end%>
					</td>
					<td><%= booking.start_datetime.strftime("%d %B %Y - %I:%M %P ") %></td>
					<td><%= booking.end_datetime.strftime("%d %B %Y - %I:%M %P ") %></td>
				</tr>
				<% end %>
			</table>
		</div>

		<div class="col-md-5 ">			
			<% if can? :update, @venue %>
				<div class="page-header">
					<h3>Add a Booking</h3>
				</div>
				<div class="well">
				<%= form_for @venue_booking do |f| %>
					
					<%= f.hidden_field :venue_id, value: @venue.id %>

					<%= f.label "Starting at" %>
				<%= f.text_field :start_datetime, id: "startDatetime" %> <br>

				<%= f.label "Ending at" %>
				<%= f.text_field :end_datetime, id: "endDatetime" %> <br/>

				<!-- f.datetime_select :end_datetime, ampm: true, minute_step: 15  -->
						
					<%= f.submit "Book", class: "btn btn-primary"%>

				<% end %>
				</div>
			<% end %>
		</div>

	</div>

	<%= link_to "Back", venues_path %>


</div>