config/routes.rb
Rails.application.routes.draw do

  resources :event_bookings
  devise_for :users, controllers: {registrations: 'registrations'}

  scope "/admin" do 
    resources :users
  end

  resources :venues

  resources :venue_bookings

  get 'events/my_events'
  resources :events do 
    resources :event_bookings
  end
  resources :categories

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :event_categories
	has_many :events, through: :event_categories
	

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def show
		@category = Category.find(params[:id])
		@events = @category.events
		@categories = Category.all
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_tab.html.erb
<ul class="nav nav-tabs" >
	<li role="presentation" > <a href="/events">Home</a></li>
	
	<% if can? :my_events, Event.new %>
		<li role="presentation"> <a href="/events/my_events">My Events</a></li>
	<%end%>

  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Categories <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <% @categories.each do |category| %>
      	<li><%= link_to category.name.capitalize, category_path(category) %></li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/categories/show.html.erb
<div class="jumbotron jumbotron-events" >
  <div class="container">
    <div style="margin-top: 100px">
	<div class="page-header text-center">
		<p>
			<% if params[:search] == nil %>
				<h3><%= @category.name.capitalize %></h3>
			<% else %>
				<h3>Events with "<%= params[:search] %>" : </h3>
			<% end %>
		</p>
	</div>
	<div class="text-center">
		<h4><% if can? :my_events, Event.new %>
			Goto <%= link_to "My Events", events_my_events_path %> 
			<%end%>
			<% if can? :create, Event.new %>
				or <%= link_to "Create Event", new_event_path, class: "btn btn-info" %>
			<% end %>
		</h4>

		<%= form_tag(events_path, method: "get", class: "form-inline") do %>
			<%= text_field_tag :search, params[:search], prompt: "Enter a keyword...", class: "form-control" %>
			<%= submit_tag "Search",class: "btn btn-default" %>
		<% end %>
	</div>
	</div>
  </div>
</div>


<div class="container">
	<%= render 'tab' %>

	
	<div class="row">
		<% @events.each do |event|%>
		<div class="col-sm-6 col-md-3">
			<div class="card">
			  <%= image_tag(event.avatar.url, height: "150px", width: "100%") %>
			  <div class="card-padding">
			  	<div class="row">
			  		<h4 style="margin-left:8px;"><%= link_to "#{event.name}", event_path(event) %></h4>
			  	</div>
		        
		        <div class="row">
		        	<div class="col-md-8">
		        		<p class="text-left"><%= event.categories.pluck(:name).map { |e| e.capitalize }.join(', ') %></p>
		        	</div>
		        	<div class="col-md-4">
		        		<p class="text-center">
		        			<%= link_to event_path(event) do%>
								<span class="glyphicon glyphicon-eye-open"></span>
							<%end%>
							<% if can? :update, event %>
								<%= link_to edit_event_path(event) do %>
									<span class="glyphicon glyphicon-pencil"></span>
								<%end%>
								<%= link_to event_path(event), method: :delete, data: {confirm: "Are you sure?"} do %>
									<span class="glyphicon glyphicon-trash"></span>
								<%end%>	
							<% end %>
		        		</p>
		        	</div>
		        </div>

		        <div class="row">
		        	<div class="col-md-6 ">
		        		<p class="text-center well well-sm"> <small><%= event.end_datetime.strftime("%d %b %Y") %></small></p>
		        	</div>
		        	<div class="col-md-6" style="margin-top:2px">
		        		<p ><a href="/events/<%= "#{event.id}" %>" class="btn btn-danger" role="button" style="border: none; color: white;">Buy Tickets</a></p>
		        	</div>
		        </div>
			  </div>
			</div>
		</div>
		<%end%>
	</div>

</div>